# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/SHAIKYASIR/d4afd4987e7667449e61e354a8023da5/untitled0.ipynb
"""

import pandas as pd
import numpy as np

print("Stocks of yasir")
money=[90,82,73,94,100]
Stock_name=['IBM','INFOSYS','TATA','META','GOOGLE']
ind=pd.Series(money,index=Stock_name)
dt=pd.DataFrame(
    {
        "STOCKS":pd.Series(Stock_name),
        "MONEY":pd.Series(money),
        "TERM PLAN":pd.Series(['A','B','C','A','A']),
        "STATUS":'Profit',
        "ANALYSIS":np.array([1]*5),
    }
)
print(dt)



print("Stocks of yasir")
money=[90,82,73,94,100]
Stock_name=['IBM','INFOSYS','TATA','META','GOOGLE']
ind=pd.Series(money,index=Stock_name)
dt=pd.DataFrame(
    {
        "STOCKS":pd.Series(Stock_name),
        "MONEY":pd.Series(money),
        "TERM PLAN":pd.Series(['A','B','C','A','A']),
        "STATUS":'Profit',
        "ANALYSIS":np.array([1]*5),
    }
)
print(money)
mon=np.mean(money)
mon1=np.median(money)

print("Mean money is:",mon)
print("Median money is:",mon1)
x=np.percentile(money, 80, axis=None,interpolation='midpoint')
print("Percentile function:",x)
y=np.var(money, axis=None, dtype=None, ddof=0)
print("Variance function:",y)
z=np.std(money, axis=None, dtype=None, ddof=0)
print("Standard deviation:",z)

print("Stocks of yasir")
money=[90,82,73,94,100]
Stock_name=['IBM','INFOSYS','TATA','META','GOOGLE']
ind=pd.Series(money,index=Stock_name)
dt=pd.DataFrame(
    {
        "STOCKS":pd.Series(Stock_name),
        "MONEY":pd.Series(money),
        "TERM PLAN":pd.Series(['A','B','C','A','A']),
        "STATUS":'Profit',
        "ANALYSIS":np.array([1]*5),
    }
)
dt1=pd.DataFrame(
    {
        "Remarks":pd.Categorical(["PLAN SUCCESS"]),
    }
)
dtfl=pd.concat([dt,dt1])
print(dtfl)